# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.7.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: lein clean
      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      # build the html
      - run: lein run

      # setup git
      - run: git config --global user.email "circleci-autobuild@ddft.wiki"
      - run: git config --global user.name "CircleCI Autobuild"

      - add_ssh_keys:
          fingerprints:
            - "ff:ea:c3:fe:29:c2:eb:eb:8c:48:a7:b2:3a:c9:a5:54"

      # copy it to the sub repo
      - run: pushd ~ && git clone git@github.com:ddftwiki/ddftwiki.github.io && popd
      - run: rm -rf ~/ddftwiki.github.io/*
      - run: cp -r resources/public/* ~/ddftwiki.github.io/

      # deploy it
      - deploy:
          name: "Deploy to ddftwiki.github.io"
          command: |
            pushd ~/ddftwiki.github.io && git checkout master && git add -A && git commit --allow-empty -m "deploying" && git push -u origin master -f && popd
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
